Devel/justin
pioneers/atalanta pull request #7
Opened 2016-09-20 06:14 UTC by greenkee

Changed State Manager's state to a dictionary

2016-09-20 06:49 UTC, yizow commented on testy/stateManager.py
> +
remove unnesscary new line

2016-09-20 06:49 UTC, yizow commented on testy/stateManager.py
> +  def getValue(self, string):
These two functions don't add much value by themselves; too short.

2016-09-20 06:50 UTC, yizow commented on testy/stateManager.py
> +  def setValue(self, string, value):
See above

2016-09-20 06:50 UTC, yizow commented on testy/stateManager.py
> +  def getValue(self, string):
Should probably change the argument list to be "self, key"

2016-09-20 06:52 UTC, yizow commented on testy/stateManager.py
> +        self.processMapping[PROCESS_NAMES.STUDENT_CODE].send(self.getValue(request[1]))
Consider moving a lot of this code into the self.getValue function

2016-09-20 06:52 UTC, yizow commented on testy/stateManager.py
> +        self.processMapping[PROCESS_NAMES.STUDENT_CODE].send(self.setValue(request[1], request[2]))
See above

2016-09-20 06:52 UTC, yizow commented on testy/stateManager.py
> +        # self.state[0] -= 1
Remove the commented out lines. Github history will track removed lines.

2016-09-20 06:53 UTC, yizow commented on testy/studentCode.py
> +  print("DAT:", 1.0/response)
Add newline at end of file. 
Has semantic meaning apparently; google for more details.

2016-09-20 06:55 UTC, yizow requested changes
Respond to comments, either change code according to comment, or comment back explaining why the comment is incorrect. 

When finished:
git add -u;
git commit --amend;
git push -f (make sure you're pushing to devel/justin

2016-09-22 02:59 UTC, bodiddles reviewed
Yizhe, we have to eventually change indents to 4 spaces eventually.

2016-09-22 03:12 UTC, merged